version: "3.1"

networks:
  network-nutrisync:
    name: network-nutrisync

services:
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    command: [--auth]
    networks:
      - network-nutrisync
    container_name: mongo-nutrisync
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - nutrisync-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express-nutrisync
    networks:
      - network-nutrisync
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}

  redis-cache:
    image: redis:alpine
    container_name: redis_nutrisync
    networks:
      - network-nutrisync
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  nutrisync-data:
    name: nutrisync-data
