start: 
	echo "Creating base container image"
	docker-compose up -d

stop:
	echo "Stoping containers"
	docker-compose down

destroy: 
	echo "Stopping containers and removing volumes"
	docker-compose down -v